# Generated by Django 5.2.6 on 2025-09-17 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('idade', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id_desafio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='app.grupo')),
            ],
            options={
                'db_table': 'desafios',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('id_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('id_remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['hora'],
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id_preferencia', models.AutoField(primary_key=True, serialize=False)),
                ('esportes', models.CharField(blank=True, max_length=200)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('turno', models.CharField(blank=True, max_length=50)),
                ('idade_parc', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preferencias',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id_parceiros', models.AutoField(primary_key=True, serialize=False)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parceiros', to=settings.AUTH_USER_MODEL)),
                ('preferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.preferencia')),
            ],
            options={
                'db_table': 'parceiros',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id_ranking', models.AutoField(primary_key=True, serialize=False)),
                ('pontuacao_total', models.IntegerField(default=0)),
                ('esporte_prat', models.CharField(blank=True, max_length=150)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='Conclusao',
            fields=[
                ('id_conclusao', models.AutoField(primary_key=True, serialize=False)),
                ('data_conclusao', models.DateField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to=settings.AUTH_USER_MODEL)),
                ('id_desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='app.desafio')),
            ],
            options={
                'db_table': 'conclusoes',
                'unique_together': {('id_desafio', 'id_usuario')},
            },
        ),
        migrations.CreateModel(
            name='GrupoAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_de_grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grupo_admins',
                'unique_together': {('grupo', 'usuario')},
            },
        ),
    ]
