# Generated by Django 5.2.7 on 2025-10-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemGrupo',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='app.grupo')),
                ('id_remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_grupo_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagens_grupo',
                'ordering': ['hora'],
            },
        ),
    ]
