# Generated by Django 5.2.7 on 2025-11-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='idade_parc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='nivel',
            field=models.CharField(blank=True, choices=[('I', 'Iniciante'), ('M', 'Intermediário'), ('A', 'Avançado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='turno',
            field=models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1),
        ),
    ]
