# Generated by Django 5.2.1 on 2025-11-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='idade_parc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
